### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by Juninho77**
Fixed victim's mask sprite not updating if facehugger was thrown.
Fixed facehugger not properly attaching to monkey faces.
Added message if the facehugger fails to tear a mask off its target's face.

Fixed the following bugs:
1. Shield generator stays "On" once deactivated, generating some of the shield still. 
1. "Ejecting" a magazine from an M41A rifle causes a box to open asking who's magazine you want to eject. http://www.colonial-marines.com/viewtopic.php?f=116&t=2160
2. Flashbangs affect aliens
3. Aliens can ventcrawl out of welded closets
4. Holding facehuggers lets you unweld vents http://www.colonial-marines.com/viewtopic.php?f=116&t=2132
5. Aliens can use fireaxes... Ask Abby for how.

### CODE REVIEW

**Comment by rahlzel** [comment]
I just now noticed this.

We don't use this repo anymore, but I might still be able to carry over your fixes to our private one.

**Comment by apophis775** [comment]
Juniho, this is our code release repo.  Message me over skype.

**Comment by apophis775** [comment]
Juniho, this is our code release repo.  Message me over skype.

**Comment by rahlzel** [comment]
Just tossing this in here - conflicts:

```
Checking patch code/modules/mob/living/carbon/carbon.dm...
Hunk #1 succeeded at 396 (offset -4 lines).
Checking patch code/controllers/_DynamicAreaLighting_TG.dm...
Checking patch code/modules/projectiles/gun.dm...
Checking patch code/modules/projectiles/guns/twohanded_projectile.dm...
Hunk #1 succeeded at 204 (offset -4 lines).
Checking patch code/modules/mob/living/carbon/alien/special/alien_embryo.dm...
Checking patch code/modules/marines/shuttles.dm...
Hunk #1 succeeded at 174 (offset 2 lines).
Checking patch code/modules/projectiles/guns/projectile.dm...
Checking patch code/modules/projectiles/guns/twohanded_projectile.dm...
Checking patch code/game/objects/structures/crates_lockers/closets.dm...
Checking patch code/game/objects/structures/crates_lockers/closets.dm...
error: while searching for:
    for(var/obj/structure/closet/closet in get_turf(src))
        if(closet != src)
            return 0
    return 1

/obj/structure/closet/proc/dump_contents()

error: patch failed: code/game/objects/structures/crates_lockers/closets.dm:39
error: while searching for:
        if(welded)
            overlays += "welded"
    else
        icon_state = icon_opened
error: patch failed: code/game/objects/structures/crates_lockers/closets.dm:284
Checking patch code/modules/marines/Marine_Weapons_V2.dm...
error: while searching for:
        set category = "Object"
        set name = "Eject current magazine"
        set src in usr
        playsound(usr, 'sound/weapons/smg_empty_alarm.ogg', 40, 1)
        usr << "\blue You eject the magazine from \the [src]!"
        empty_mag.desc = "There are [getAmmo()] shells left"

        if(usr.canmove && !usr.stat && !usr.restrained())
            var/obj/item/ammo_magazine/AM = empty_mag
            for (var/obj/item/ammo_casing/AC in loaded)
                AM.stored_ammo += AC
                loaded -= AC
                AM.loc = get_turf(src)
                empty_mag = null
                update_icon()
/*
    verb/toggle(mob/user)
        set category = "Object"

error: patch failed: code/modules/marines/Marine_Weapons_V2.dm:219
Checking patch code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm...

Checking patch code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm...
Checking patch code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm...
Hunk #1 succeeded at 156 (offset 14 lines).
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm...
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm...
error: while searching for:
    for(var/mob/O in viewers(src, null))
        O.show_message(text("\green <B>[src] begins to twist and contort!</B>"), 1)
    if(mind)    mind.transfer_to(new_xeno)

    del(src)



error: patch failed: code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm:155
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/spitter.dm...
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm...
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/runner.dm...
Checking patch code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm...

Checking patch code/modules/mob/living/carbon/carbon.dm...
Checking patch code/game/objects/structures/tables_racks.dm...

Checking patch code/modules/mob/living/carbon/alien/special/facehugger.dm...
Hunk #1 succeeded at 345 (offset -15 lines).
Checking patch code/modules/mob/living/carbon/alien/powers.dm...
Checking patch code/modules/reagents/reagent_containers/hypospray.dm...
Checking patch code/modules/mob/living/carbon/alien/special/facehugger.dm...
Checking patch code/modules/marines/Marine_Weapons_V2.dm...

error: while searching for:
        set category = "Object"
        set name = "Eject current magazine"
        set src in usr

        playsound(usr, 'sound/weapons/smg_empty_alarm.ogg', 40, 1)
        usr << "\blue You eject the magazine from 
        empty_mag.desc = "There are [getAmmo()] shells left"

error: patch failed: code/modules/marines/Marine_Weapons_V2.dm:219
Checking patch code/game/objects/items/weapons/grenades/flashbang.dm...
error: while searching for:
                    M << "\red Your ears start to ring!"
            M.update_icons()



/obj/item/weapon/grenade/flashbang/clusterbang//Created by Polymorph, fixed by Sieve
    desc = "Use of this weapon may constiute a war crime in your area, consult your local captain."
    name = "clusterbang"

error: patch failed: code/game/objects/items/weapons/grenades/flashbang.dm:99
Checking patch code/game/objects/items/weapons/grenades/flashbang.dm...
Checking patch code/modules/marines/Marine_Weapons_V2.dm...
Checking patch code/game/machinery/shieldgen.dm...
Checking patch code/modules/mob/living/carbon/carbon.dm...
error: while searching for:
        src << "You can't vent crawl whilst in critical condition!"
        return













    /*if(var/obj/structure/closet in loc)

        src << "You can't vent crawl from inside a closet!"
        return */

    if(vent_found) // one was passed in, probably from vent/AltClick()
        if(vent_found.welded)

error: patch failed: code/modules/mob/living/carbon/carbon.dm:238

Checking patch code/modules/mob/living/carbon/carbon.dm...
Checking patch code/ATMOSPHERICS/components/unary/vent_pump.dm...
```

The problem is that you're using an outdated version of our source to make fixes. Some of these will work fine. Others won't if we've made changes to them.

**Pull request closed without merging**
